### ISSUE TITLE
(Millions of) duplicated sequences in Nextstrain-open aligned.fasta.zst

### ISSUE THREAD

**Issue by theosanderson** [nextstrain/ncov-ingest#387]
Thanks so much for Nextstrain open, which is a tremendous contribution to the community.

The aligned.fasta.zst contains 14.5M entries. I believe these basically represent two copies each of all the 7M open data sequences.

As an example:

```
zstdcat ~/Desktop/aligned.fasta.zst | grep ">" | grep "LR882161"
>LR882161
>LR882161
```

I haven't checked the other alignment files

Thanks again!

**Comment by emmahodcroft** [comment]
Thanks so much for flagging this Theo - that doesn't seem right! Can I ask, on the off-chance you were working with these recently and they were ok, is there a date you know they seemed to be without duplicates? (No worries if not!)

**Comment by theosanderson** [comment]
Really sorry, but I'm afaid I haven't really been using these lately. I saw some other issues on this repo that would suggest it hasn't been like this forever, but I can't help more than that sadly. The metadata file has ~7M rows.

**Comment by joverlee521** [comment]
Thanks for reporting this! There was an issue in our last full Nextclade run that duplicated our cache. We are doing another full Nextclade run today that should fix this issue.

**Comment by theosanderson** [comment]
Thank you!

**Comment by tsibley** [comment]
@emmahodcroft FWIW (maybe future issues), we store a `recordcount` metadata field on the S3 objects, and the objects are versioned, so walking back thru the versions shows when the doubling occurred:

```
GxpweaA2AZgILQriyonn1NvGQPQdOjr8 28916164 Wed, 11 Jan 2023 10:25:42 GMT
nkr3kx4hZvoKLGcweb1zvgLXoMucj3AY 14472298 Mon, 09 Jan 2023 00:01:47 GMT
```

that's version id, record count (really line count), and modified date.

**Comment by corneliusroemer** [comment]
My fault - sorry @theosanderson! The issue was known but not yet fixed. It should be fixed in a few hours.

**Comment by corneliusroemer** [comment]
I just confirmed that this issue has been resolved via:
```sh
aws s3 cp s3://nextstrain-data/files/ncov/open/aligned.fasta.zst - | zstdcat | seqkit seq -n | sort --parallel=4 | uniq -d | wc -l
```

which returned 0 as expected for no duplicates.

We currently have 7,285,743 open sequences.

**Comment by theosanderson** [comment]
Hello, it looks like these files are very short of sequences now :) 🎢  

```
wget https://data.nextstrain.org/files/ncov/open/aligned.fasta.zst
zstdcat aligned.fasta.zst | wc -l
29200
```

**Comment by corneliusroemer** [comment]
Alright, I can confirm that this new issue has been fixed @theosanderson 

>Hello, it looks like these files are very short of sequences now :) 🎢
>```
>wget https://data.nextstrain.org/files/ncov/open/aligned.fasta.zst
>zstdcat aligned.fasta.zst | wc -l
>29200
>```

We're back to 7,299,692 sequences

**Comment by corneliusroemer** [comment]
Cause some issues in covSpectrum too. Another way I could have noticed: https://github.com/GenSpectrum/LAPIS/issues/86#event-8476734545
